### ISSUE TITLE
No module named 'geetools.ui' when importing from ipygee on google colab

### ISSUE THREAD

**Issue by ditirodt** [gee-community/geetools#238]
I am trying to import all from ipygee on google colab and No module named 'geetools.ui' error

How I import: `from ipygee import *`

Please assist on this, here is the [link ](https://colab.research.google.com/drive/1FVdWvJFMEhgY4NPgEY5_tZD3_WzMTjPv?usp=sharing)to the colab

**Comment by ditirodt** [comment]
I am trying to use line chart, here is the code, just trying to plot
`selected_roi_ndvi = chart.Image.series(**{'imageCollection': scaled_ndvi,
                                   'region': roi,
                                   'reducer': ee.Reducer.mean(),
                                   'scale': 1000,
                                   'xProperty': 'system:time_start'})
selected_roi_ndvi.renderWidget(width='50%')`

**Comment by 12rambau** [comment]
ok then you need to downgrade the geetools version to <1 as we are not supporting this ipygee interface anymore.
