### ISSUE TITLE
offset_by_xyz charting

### ISSUE THREAD

**Issue by fitoprincipe** [gee-community/geetools#363]
related to https://github.com/gee-community/geetools/issues/362.

It's a common request to plot values where x-axis starts in 0 and increases according to the "time distance" (offset) to the first element.

I already coded a mock, but I was wondering if we should do it at all 🤔it's not hard to do it on the client-side, the user can map over the dates and compute the distance to the first date.

**Comment by 12rambau** [comment]
I know that matplotlib already have this fully integrated as you can do: 

```python
import matplotlib.dates as mdates

ax.xaxis.set_major_formatter(mdates.DateFormatter("%Y-%m-%d"))
ax.xaxis.set_major_locator(mdates.DayLocator(interval=2))
```

And I guess other ploting libs have it as well. 
IMHO I would leave it as a client side thing
