### ISSUE TITLE
`ee.ImageCollection.reduceRegions` (with a trailing `s`)

### ISSUE THREAD

**Issue by fitoprincipe** [gee-community/geetools#367]
As a follow up of https://github.com/gee-community/geetools/pull/359.

The vanilla `ee.Image.reduceRegions` method takes a `ee.FeatureCollection` as a param and returns the outputs as columns of the same table.

My proposal is: 

`ee.ImageCollection.reduceRegions` also takes a `ee.FeatureCollection` as a param and returns the outputs of each image as columns of the same table where the `system:index` of features will be repeated, and include the image's properties. It should add 2 new columns: `table_id` and `image_id`.

| image_id | table_id | B4 | B5 | ADM0_NAME | CLOUD_COVER |
| - | - | - | - | - | - |
| sentinel2_id_1 | feature_1 | 0.5 | 0.1 | "Argentina" | 60 |
| sentinel2_id_2 | feature_1 | 0.15 | 0.2 | "Argentina" | 50 |
| sentinel2_id_3 | feature_1 | 0.25 | 0.3 | "Argentina" | 40 |
| sentinel2_id_1 | feature_2 | 0.35 | 0.4 | "Brazil" | 60 |
| sentinel2_id_2 | feature_2 | 0.45 | 0.5 | "Brazil" | 50 |
| sentinel2_id_3 | feature_2 | 0.55 | 0.6 | "Brazil" | 40 |

This output will be easy to post-process using filters and reducers.

One of my question is, what to do with system properties, like `system:time_start`? 🤔 sounds like this should be included, but what about others, like `system:footprint` or `system:band_names`

**Comment by 12rambau** [comment]
but the output remains a featureCollection right ?

**Comment by fitoprincipe** [comment]
exactly, the output will be a `ee.FeatureCollection`
