### ISSUE TITLE
`maxPixels` in reducing methods for charting

### ISSUE THREAD

**Issue by fitoprincipe** [gee-community/geetools#370]
I'm starting to implement the new method for charting, like `ee.ImageCollection.geetools.datesByBands`, in a [new library](https://github.com/fitoprincipe/pygalgee) that will use [`pygal`](https://github.com/Kozea/pygal) as the charting library. The new package will try to mimic the namespaces of GEE JS API. I started by testing `datesByBands` using the same test as https://github.com/gee-community/geetools/blob/1273b7154bbded6ad9bc15d3eb08a6ebe40283ee/tests/test_ImageCollection.py#L418. However, although it seems to pass in this package, in my test I get

> ee.ee_exception.EEException: Image.reduceRegion: Too many pixels in the region. Found 614260390427, but maxPixels allows only 10000000.

which can be overcome by setting a higher `maxPixels` in the reduction. But unfortunately the method doesn't have the parameter.

Although it might be solved by https://github.com/gee-community/geetools/pull/359, I think it should also be solved in the method.

**Comment by 12rambau** [comment]
Do you think it would worth the shot to actually expose all the reducer parameters ?

**Comment by fitoprincipe** [comment]
I think it does. Those params have been there for long and I don't think we should worry about them changing frequently.
