### ISSUE TITLE
Recommended feature of the `ImageCollectionAccessor.groupInterval` and `ImageCollectionAccessor.reduceInterval` methods.

### ISSUE THREAD

**Issue by framunoz** [gee-community/geetools#401]
# Explanation of the problem
I have used the methods mentioned in the title, and I noticed two things:
1. There is no option to filter empty collections in the `ImageCollectionAccessor.groupInterval` method.
2. The last issue raises an exception in the `ImageCollectionAccessor.reduceInterval` method: if there are no images, then the reduce method raise an error.

The former would be a one-off problem, but I think the latter is a problem: If I want to reduce an image specifically in 1-day durations (as is my case), then the method always fails (given the current product I choose).

To solve these issues, I propose the following changes:

## Add a new parameter in the `ImageCollectionAccessor.groupInterval` method

Here is my proposed implementation:
```python
def newGroupInterval(self, unit: str = "month", duration: int = 1, dropEmpties: bool = False) -> ee.List:
    ic = self._obj.sort("system:time_start")

    timeList = ic.aggregate_array("system:time_start")
    start, end = timeList.get(0), timeList.get(-1)
    DateRangeList = ee.DateRange(start, end).geetools.split(duration, unit)
    imageCollectionList = DateRangeList.map(
        lambda dr: ic.filterDate(ee.DateRange(dr).start(), ee.DateRange(dr).end())
    )

    # Here start my changes
    if dropEmpties:
        def add_size(ic):
            ic = ee.ImageCollection(ic)
            return ic.set({"size": ic.size()})
            
        imageCollectionList = (
            imageCollectionList
            .map(add_size)
            .filter(ee.Filter.gt("size", 0))
        )
    # Aaand end my changes

    return ee.List(imageCollectionList)
```

I add the `dropEmpties` parameter, which attaches a "size" in the ImageCollections and then, I filter the collections that are empty. I don't know if this is the best way to solve this problem, and I tried to use `ee.Filter.notNull`, but I failed 😥.

## Fixing and adding a new parameter in the `ImageCollectionAccessor.groupInterval` method

Using the last change, I propose the following change:
```python
def newReduceInterval(
    self,
    reducer: str | ee.Reducer = "mean",
    unit: str = "month",
    duration: int = 1,
    dropNa: bool = False,
) -> ee.ImageCollection:
    # create a list of image collections to be reduced
    # Every subcollection is sorted in case one use the "first" reducer
    imageCollectionList = self.groupInterval(unit, duration, dropNa)

    # create a reducer from user parameters
    red = getattr(ee.Reducer, reducer)() if isinstance(reducer, str) else reducer

    # Here start my changes
    def reduce_without_na(ic):
        ic = ee.ImageCollection(ic)
        bandNames = ic.first().bandNames()
        image = ic.reduce(red)
        timeList = ic.aggregate_array("system:time_start")
        return (
            image
            .rename(bandNames)
            .set("system:time_start", timeList.get(0),
                 "system:time_end", timeList.get(-1))
        )

    def reduce_with_na(ic):
        ic = ee.ImageCollection(ic)
        bandNames = ic.first().bandNames()
        image = ic.reduce(red)
        timeList = ic.aggregate_array("system:time_start")
        image = ee.Algorithms.If(
            # If there are any image...
            ic.size(),
            # Return the image with the new properties
            (
                image.rename(bandNames)
                .set("system:time_start", timeList.get(0),
                     "system:time_end", timeList.get(-1))
            ),
            # Otherwise, return the empty image
            image
        )
        return image

    reduce = reduce_without_na if dropNa else reduce_with_na
    # Aaand end my changes

    reducedImagesList = imageCollectionList.map(reduce)

    # set back the original properties
    ic = ee.ImageCollection(reducedImagesList).copyProperties(self._obj)

    return ee.ImageCollection(ic)
```

Note that in the first line, I use the new change mentioned above. In this case, you can just use the `reduce_with_na` auxiliary function, solve the mentioned problem, and omit the use of the proposed change. But this generates a (minor) problem: [it uses `ee.Algorithms.If`](https://developers.google.com/earth-engine/guides/best_practices#avoid_eealgorithmsif), and it could be really memory intensive. That is the reason I proposed the other change.

# Last words

The reason I don't propose a PR, is because I don't know how to test using GEE. But I think this could be a problem that may affect other people.

**Comment by 12rambau** [comment]
Hi @framunoz and thank you very much for the detailed issue, I the time you spend building up this shoulf be rewarded and you should definitely author the potential PR. 

> The reason I don't propose a PR, is because I don't know how to test using GEE. But I think this could be a problem that may affect other people.

This very WE I updated the CONTRIBUTING.md file with an extra section about GEE initialization; https://geetools.readthedocs.io/en/latest/setup/contribute.html#initialize-gee-available I know it's still full of typos but at least it exist now, would it help building a PR ? 

> There is no option to filter empty collections in the ImageCollectionAccessor.groupInterval method.

So my understanding is that you are blocked when the `groupInterval` returns empty collection that cannot obviously be transformed into an image in `reduceInterval` ? 
If that's the case then the modification you proposed for `groupInterval` seems very logical, I would even make it the default behaviour without adding any extra parameters. 

My only comments are: 
- @fitoprincipe and myself are trying to hide actions from geetools in the final output, thus we mostly create fake names for any constructed properties that are not carried out in the final output. That would be the case for this "size" new property. On the other hand using uuid as I was doing in the refactoring is a problem as the method cannot be mapped anymore. So maybe we could use a very unlikely convention like `__geetools_generated_size__` whi would work perrfectly, avoid the use of a client size method and will never conflict with existing parameters. 
- why do you need the second upgrade in `reduceInterval` ? if there are no empty image collection outputed by `groupInterval` the bug shoud be gone ?

**Comment by framunoz** [comment]
Hi @12rambau, thank you for the message. I'm going to answer the questions:

> This very WE I updated the CONTRIBUTING.md file with an extra section about GEE initialization; https://geetools.readthedocs.io/en/latest/setup/contribute.html#initialize-gee-available I know it's still full of typos but at least it exist now, would it help building a PR ?

Actually, the updated contribution workflow helps me now to initialize gee in my local machine, thank you very much!

> So my understanding is that you are blocked when the groupInterval returns empty collection that cannot obviously be transformed into an image in reduceInterval ?
If that's the case then the modification you proposed for groupInterval seems very logical, I would even make it the default behaviour without adding any extra parameters.

Yes, that is the problem. And well, yes, it could be better return the filtered collection instead of adding new parameters.

> @fitoprincipe and myself are trying to hide actions from geetools in the final output, thus we mostly create fake names for any constructed properties that are not carried out in the final output. That would be the case for this "size" new property. On the other hand using uuid as I was doing in the refactoring is a problem as the method cannot be mapped anymore. So maybe we could use a very unlikely convention like __geetools_generated_size__ whi would work perrfectly, avoid the use of a client size method and will never conflict with existing parameters.

Thank you for the comment! I also fell that it's something annoying left that property in the image collection. Futhermore, I can imagine that in the future the size can be changed and that property it's not updated. But in that case, the code should be like this?
```python
def add_size(ic):
    ic = ee.ImageCollection(ic)
    return ic.set({"__geetools_generated_size__": ic.size()})
    
imageCollectionList = (
    imageCollectionList
    .map(add_size)
    .filter(ee.Filter.gt("__geetools_generated_size__", 0))
)
```

> why do you need the second upgrade in reduceInterval ? if there are no empty image collection outputed by groupInterval the bug shoud be gone ?

That upgrade is in the case the user will want to mantain the current collections (it was the first version, actually). But now that you mention it, if we left the `groupInterval` droping the empties collection as default, then the change makes no sense.

**Comment by 12rambau** [comment]
I would set the size property name as a variable in one single place to leave us the possibility of changing it in the future if needed.

**Comment by framunoz** [comment]
I made the PR #406, where I include the tests for the before mentioned in this issue:

> There is no option to filter empty collections in the ImageCollectionAccessor.groupInterval method.
The last issue raises an exception in the ImageCollectionAccessor.reduceInterval method: if there are no images, then the reduce method raise an error.

Additionally, I add a test for the first comment:

> fitoprincipe and myself are trying to hide actions from geetools in the final output, thus we mostly create fake names for any constructed properties that are not carried out in the final output. That would be the case for this "size" new property. On the other hand using uuid as I was doing in the refactoring is a problem as the method cannot be mapped anymore. So maybe we could use a very unlikely convention like __geetools_generated_size__ whi would work perrfectly, avoid the use of a client size method and will never conflict with existing parameters.

By the way, I don't know if the way that I solve the issue is the most efficient.

**Comment by 12rambau** [comment]
you did it without realizing meaning the problem was my explanation.
