### ISSUE TITLE
band name error

### ISSUE THREAD

**Issue by A-Marambe** [gee-community/geetools#68]
cloud masking leads into this error

"
HttpError: <HttpError 400 when requesting https://earthengine.googleapis.com/v1alpha/projects/earthengine-legacy/value:compute?prettyPrint=false&alt=json returned "Image.select: Pattern 'pixel_qa' did not match any bands.". Details: "Image.select: Pattern 'pixel_qa' did not match any bands.">"

is it due to Landsat SR band name convention changed as 'QA_PIXEL',

**Comment by fitoprincipe** [comment]
Hello @A-Marambe , what is the code that returned that error?

**Comment by A-Marambe** [comment]
Hello, it is cloud masking, 
`mask_l8SR_all = cloud_mask.landsatSR()
mask_l8SR_cloud = cloud_mask.landsatSR(['cloud'])` 
I just following the example notebook

**Comment by 12rambau** [comment]
As the code base as drasticly changed since this issue was open I took the liberty of closing it.
